map_file: null
map_resolution: null

random_seed: 42 # Seed for RNG
n_threads: 8    # Number of threads used

log_file: lpo_accuracy.txt     # Path to log file
landmarks_file: landmarks.npy  # Path to output file

target_accuracy: 0.015   # Target std accuracy

# GA params
max_inner_iter: 200    # Number of max inner iterations
max_landmarks: 30      # Max number of landmarks that can be placed
init_landmarks: 8      # Initial number of landmarks
population_size: 30    # Number of particles
nlls_samples: 500      # Number of samples to estimate the localization accuracy
heatmap_progress: True # Show a progressbar for heatmap generation
